### ISSUE TITLE
Usage - text for users

### ISSUE THREAD

**Issue by StuartNewson** [BritishTrustForOrnithology/BTOAcousticPipelineTools#1]
I have had a couple of non-R users who have struggled to run the app, because they didn't realise that they had to define the path and how to do that. In both cases, they needed to define the path.

I am not sure how best to word this, but I was wondering if we could clarify what to do if they need to define the path.

At the moment the Usage text says: "To run the app, with R/RStudio open, open the script file called 'launch_shiny_app.R' and run it. You should not need to change any of the code, but if you are experience with R and move the 'app.R' file you will need to update path_to_app so that it points to where 'app.R' is located."

**Comment by btosimongillings** [comment]
usage instructions improved on readme and in launch_shiny_app.R. Also a warning added to app.R to warn against direct use.
